schema_version: 1

board:
  gpio_device: &gpio_device /dev/gpiochip0
  gpio_chip_name: &gpio_chip_name ""
  gpio_chip_label: &gpio_chip_label ""
  i2c_device: &i2c_device /dev/i2c-1
  robot_config: &robot_config /tmp/xwalk-init-angles.config
  pcm_device: &pcm_device default
  mixer_device: &mixer_device default
  mixer_element: &mixer_element PCM

ai:
  piper_executable: piper
  piper_model: en_US-amy-low.onnx

sequences:
  button-event:
    arguments: [30, *gpio_device, *gpio_chip_name, *gpio_chip_label]
  init-angles:
    arguments:
      - *i2c_device
      - *gpio_device
      - *gpio_chip_name
      - *gpio_chip_label
      - *robot_config
  motor-robothat5:
    arguments: [1, *i2c_device]
  motor:
    arguments: [1, *i2c_device, *gpio_device, *gpio_chip_name, *gpio_chip_label]
  servo-hat:
    arguments: [1, *i2c_device, *gpio_device, *gpio_chip_name, *gpio_chip_label]
  servo:
    arguments: [1, *i2c_device]
  tone:
    arguments: [*pcm_device, *mixer_device, *mixer_element]
