use_default_settings: true

general:
  debug: false
  instance_name: xWalk local search

search:
  safe_search: 1
  autocomplete: ""
  formats:
    - json

server:
  limiter: false
  public_instance: false
  image_proxy: false
  method: GET

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: false
  searx.plugins.hash_plugin.SXNGPlugin:
    active: false
  searx.plugins.self_info.SXNGPlugin:
    active: false
  searx.plugins.tor_check.SXNGPlugin:
    active: false
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
