// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwMessageCmn.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwMessageCmn_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwMessageCmn_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xHal_5fRpi5CarXIwMessageCmn_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_xHal_5fRpi5CarXIwMessageCmn_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto;
namespace xwalk {
namespace iw {
namespace v1 {
class XClientAddress;
struct XClientAddressDefaultTypeInternal;
extern XClientAddressDefaultTypeInternal _XClientAddress_default_instance_;
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
PROTOBUF_NAMESPACE_OPEN
template<> ::xwalk::iw::v1::XClientAddress* Arena::CreateMaybeMessage<::xwalk::iw::v1::XClientAddress>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace xwalk {
namespace iw {
namespace v1 {

enum XWalkI2cOperation : int {
  XWALK_I2C_OPERATION_UNSPECIFIED = 0,
  XWALK_I2C_OPERATION_PROBE = 1,
  XWALK_I2C_OPERATION_READ = 2,
  XWALK_I2C_OPERATION_READ_REGISTER = 3,
  XWALK_I2C_OPERATION_WRITE_REGISTER = 4,
  XWalkI2cOperation_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkI2cOperation_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkI2cOperation_IsValid(int value);
constexpr XWalkI2cOperation XWalkI2cOperation_MIN = XWALK_I2C_OPERATION_UNSPECIFIED;
constexpr XWalkI2cOperation XWalkI2cOperation_MAX = XWALK_I2C_OPERATION_WRITE_REGISTER;
constexpr int XWalkI2cOperation_ARRAYSIZE = XWalkI2cOperation_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkI2cOperation_descriptor();
template<typename T>
inline const std::string& XWalkI2cOperation_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkI2cOperation>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkI2cOperation_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkI2cOperation_descriptor(), enum_t_value);
}
inline bool XWalkI2cOperation_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkI2cOperation* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkI2cOperation>(
    XWalkI2cOperation_descriptor(), name, value);
}
enum XWalkSoundOperation : int {
  XWALK_SOUND_OPERATION_PLAY = 0,
  XWALK_SOUND_OPERATION_VOLUME = 1,
  XWALK_SOUND_OPERATION_MUSIC = 2,
  XWALK_SOUND_OPERATION_STOP = 3,
  XWalkSoundOperation_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkSoundOperation_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkSoundOperation_IsValid(int value);
constexpr XWalkSoundOperation XWalkSoundOperation_MIN = XWALK_SOUND_OPERATION_PLAY;
constexpr XWalkSoundOperation XWalkSoundOperation_MAX = XWALK_SOUND_OPERATION_STOP;
constexpr int XWalkSoundOperation_ARRAYSIZE = XWalkSoundOperation_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkSoundOperation_descriptor();
template<typename T>
inline const std::string& XWalkSoundOperation_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkSoundOperation>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkSoundOperation_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkSoundOperation_descriptor(), enum_t_value);
}
inline bool XWalkSoundOperation_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkSoundOperation* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkSoundOperation>(
    XWalkSoundOperation_descriptor(), name, value);
}
enum XWalkLifecycleAction : int {
  XWALK_LIFECYCLE_ACTION_START = 0,
  XWALK_LIFECYCLE_ACTION_STOP = 1,
  XWalkLifecycleAction_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkLifecycleAction_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkLifecycleAction_IsValid(int value);
constexpr XWalkLifecycleAction XWalkLifecycleAction_MIN = XWALK_LIFECYCLE_ACTION_START;
constexpr XWalkLifecycleAction XWalkLifecycleAction_MAX = XWALK_LIFECYCLE_ACTION_STOP;
constexpr int XWalkLifecycleAction_ARRAYSIZE = XWalkLifecycleAction_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkLifecycleAction_descriptor();
template<typename T>
inline const std::string& XWalkLifecycleAction_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkLifecycleAction>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkLifecycleAction_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkLifecycleAction_descriptor(), enum_t_value);
}
inline bool XWalkLifecycleAction_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkLifecycleAction* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkLifecycleAction>(
    XWalkLifecycleAction_descriptor(), name, value);
}
enum XWalkMoveAction : int {
  XWALK_MOVE_ACTION_FORWARD = 0,
  XWALK_MOVE_ACTION_BACKWARD = 1,
  XWALK_MOVE_ACTION_DEMO = 2,
  XWalkMoveAction_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkMoveAction_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkMoveAction_IsValid(int value);
constexpr XWalkMoveAction XWalkMoveAction_MIN = XWALK_MOVE_ACTION_FORWARD;
constexpr XWalkMoveAction XWalkMoveAction_MAX = XWALK_MOVE_ACTION_DEMO;
constexpr int XWalkMoveAction_ARRAYSIZE = XWalkMoveAction_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkMoveAction_descriptor();
template<typename T>
inline const std::string& XWalkMoveAction_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkMoveAction>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkMoveAction_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkMoveAction_descriptor(), enum_t_value);
}
inline bool XWalkMoveAction_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkMoveAction* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkMoveAction>(
    XWalkMoveAction_descriptor(), name, value);
}
enum XWalkTurnDirection : int {
  XWALK_TURN_DIRECTION_LEFT = 0,
  XWALK_TURN_DIRECTION_RIGHT = 1,
  XWalkTurnDirection_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkTurnDirection_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkTurnDirection_IsValid(int value);
constexpr XWalkTurnDirection XWalkTurnDirection_MIN = XWALK_TURN_DIRECTION_LEFT;
constexpr XWalkTurnDirection XWalkTurnDirection_MAX = XWALK_TURN_DIRECTION_RIGHT;
constexpr int XWalkTurnDirection_ARRAYSIZE = XWalkTurnDirection_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkTurnDirection_descriptor();
template<typename T>
inline const std::string& XWalkTurnDirection_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkTurnDirection>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkTurnDirection_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkTurnDirection_descriptor(), enum_t_value);
}
inline bool XWalkTurnDirection_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkTurnDirection* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkTurnDirection>(
    XWalkTurnDirection_descriptor(), name, value);
}
enum XWalkCameraAxis : int {
  XWALK_CAMERA_AXIS_PAN = 0,
  XWALK_CAMERA_AXIS_TILT = 1,
  XWalkCameraAxis_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkCameraAxis_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkCameraAxis_IsValid(int value);
constexpr XWalkCameraAxis XWalkCameraAxis_MIN = XWALK_CAMERA_AXIS_PAN;
constexpr XWalkCameraAxis XWalkCameraAxis_MAX = XWALK_CAMERA_AXIS_TILT;
constexpr int XWalkCameraAxis_ARRAYSIZE = XWalkCameraAxis_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkCameraAxis_descriptor();
template<typename T>
inline const std::string& XWalkCameraAxis_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkCameraAxis>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkCameraAxis_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkCameraAxis_descriptor(), enum_t_value);
}
inline bool XWalkCameraAxis_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkCameraAxis* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkCameraAxis>(
    XWalkCameraAxis_descriptor(), name, value);
}
enum XWalkSensorType : int {
  XWALK_SENSOR_TYPE_DISTANCE = 0,
  XWALK_SENSOR_TYPE_GRAYSCALE = 1,
  XWalkSensorType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkSensorType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkSensorType_IsValid(int value);
constexpr XWalkSensorType XWalkSensorType_MIN = XWALK_SENSOR_TYPE_DISTANCE;
constexpr XWalkSensorType XWalkSensorType_MAX = XWALK_SENSOR_TYPE_GRAYSCALE;
constexpr int XWalkSensorType_ARRAYSIZE = XWalkSensorType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkSensorType_descriptor();
template<typename T>
inline const std::string& XWalkSensorType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkSensorType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkSensorType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkSensorType_descriptor(), enum_t_value);
}
inline bool XWalkSensorType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkSensorType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkSensorType>(
    XWalkSensorType_descriptor(), name, value);
}
enum XWalkCalibrationMode : int {
  XWALK_CALIBRATION_MODE_COMPLETE = 0,
  XWALK_CALIBRATION_MODE_GRAYSCALE = 1,
  XWALK_CALIBRATION_MODE_SERVO_MOTOR = 2,
  XWalkCalibrationMode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkCalibrationMode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkCalibrationMode_IsValid(int value);
constexpr XWalkCalibrationMode XWalkCalibrationMode_MIN = XWALK_CALIBRATION_MODE_COMPLETE;
constexpr XWalkCalibrationMode XWalkCalibrationMode_MAX = XWALK_CALIBRATION_MODE_SERVO_MOTOR;
constexpr int XWalkCalibrationMode_ARRAYSIZE = XWalkCalibrationMode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkCalibrationMode_descriptor();
template<typename T>
inline const std::string& XWalkCalibrationMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkCalibrationMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkCalibrationMode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkCalibrationMode_descriptor(), enum_t_value);
}
inline bool XWalkCalibrationMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkCalibrationMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkCalibrationMode>(
    XWalkCalibrationMode_descriptor(), name, value);
}
// ===================================================================

class XClientAddress final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xwalk.iw.v1.XClientAddress) */ {
 public:
  inline XClientAddress() : XClientAddress(nullptr) {}
  ~XClientAddress() override;
  explicit PROTOBUF_CONSTEXPR XClientAddress(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XClientAddress(const XClientAddress& from);
  XClientAddress(XClientAddress&& from) noexcept
    : XClientAddress() {
    *this = ::std::move(from);
  }

  inline XClientAddress& operator=(const XClientAddress& from) {
    CopyFrom(from);
    return *this;
  }
  inline XClientAddress& operator=(XClientAddress&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XClientAddress& default_instance() {
    return *internal_default_instance();
  }
  static inline const XClientAddress* internal_default_instance() {
    return reinterpret_cast<const XClientAddress*>(
               &_XClientAddress_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(XClientAddress& a, XClientAddress& b) {
    a.Swap(&b);
  }
  inline void Swap(XClientAddress* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XClientAddress* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XClientAddress* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XClientAddress>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XClientAddress& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XClientAddress& from) {
    XClientAddress::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XClientAddress* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xwalk.iw.v1.XClientAddress";
  }
  protected:
  explicit XClientAddress(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientAddressFieldNumber = 2,
    kMailBoxIdFieldNumber = 1,
    kXwalkLocalIndexFieldNumber = 3,
    kModuleTypeFieldNumber = 4,
  };
  // string client_address = 2;
  void clear_client_address();
  const std::string& client_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_address();
  PROTOBUF_NODISCARD std::string* release_client_address();
  void set_allocated_client_address(std::string* client_address);
  private:
  const std::string& _internal_client_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_address(const std::string& value);
  std::string* _internal_mutable_client_address();
  public:

  // uint32 mail_box_id = 1;
  void clear_mail_box_id();
  uint32_t mail_box_id() const;
  void set_mail_box_id(uint32_t value);
  private:
  uint32_t _internal_mail_box_id() const;
  void _internal_set_mail_box_id(uint32_t value);
  public:

  // uint32 xwalk_local_index = 3;
  void clear_xwalk_local_index();
  uint32_t xwalk_local_index() const;
  void set_xwalk_local_index(uint32_t value);
  private:
  uint32_t _internal_xwalk_local_index() const;
  void _internal_set_xwalk_local_index(uint32_t value);
  public:

  // uint32 module_type = 4;
  void clear_module_type();
  uint32_t module_type() const;
  void set_module_type(uint32_t value);
  private:
  uint32_t _internal_module_type() const;
  void _internal_set_module_type(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:xwalk.iw.v1.XClientAddress)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_address_;
    uint32_t mail_box_id_;
    uint32_t xwalk_local_index_;
    uint32_t module_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xHal_5fRpi5CarXIwMessageCmn_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// XClientAddress

// uint32 mail_box_id = 1;
inline void XClientAddress::clear_mail_box_id() {
  _impl_.mail_box_id_ = 0u;
}
inline uint32_t XClientAddress::_internal_mail_box_id() const {
  return _impl_.mail_box_id_;
}
inline uint32_t XClientAddress::mail_box_id() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XClientAddress.mail_box_id)
  return _internal_mail_box_id();
}
inline void XClientAddress::_internal_set_mail_box_id(uint32_t value) {

  _impl_.mail_box_id_ = value;
}
inline void XClientAddress::set_mail_box_id(uint32_t value) {
  _internal_set_mail_box_id(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XClientAddress.mail_box_id)
}

// string client_address = 2;
inline void XClientAddress::clear_client_address() {
  _impl_.client_address_.ClearToEmpty();
}
inline const std::string& XClientAddress::client_address() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XClientAddress.client_address)
  return _internal_client_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XClientAddress::set_client_address(ArgT0&& arg0, ArgT... args) {

 _impl_.client_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XClientAddress.client_address)
}
inline std::string* XClientAddress::mutable_client_address() {
  std::string* _s = _internal_mutable_client_address();
  // @@protoc_insertion_point(field_mutable:xwalk.iw.v1.XClientAddress.client_address)
  return _s;
}
inline const std::string& XClientAddress::_internal_client_address() const {
  return _impl_.client_address_.Get();
}
inline void XClientAddress::_internal_set_client_address(const std::string& value) {

  _impl_.client_address_.Set(value, GetArenaForAllocation());
}
inline std::string* XClientAddress::_internal_mutable_client_address() {

  return _impl_.client_address_.Mutable(GetArenaForAllocation());
}
inline std::string* XClientAddress::release_client_address() {
  // @@protoc_insertion_point(field_release:xwalk.iw.v1.XClientAddress.client_address)
  return _impl_.client_address_.Release();
}
inline void XClientAddress::set_allocated_client_address(std::string* client_address) {
  if (client_address != nullptr) {

  } else {

  }
  _impl_.client_address_.SetAllocated(client_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.client_address_.IsDefault()) {
    _impl_.client_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xwalk.iw.v1.XClientAddress.client_address)
}

// uint32 xwalk_local_index = 3;
inline void XClientAddress::clear_xwalk_local_index() {
  _impl_.xwalk_local_index_ = 0u;
}
inline uint32_t XClientAddress::_internal_xwalk_local_index() const {
  return _impl_.xwalk_local_index_;
}
inline uint32_t XClientAddress::xwalk_local_index() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XClientAddress.xwalk_local_index)
  return _internal_xwalk_local_index();
}
inline void XClientAddress::_internal_set_xwalk_local_index(uint32_t value) {

  _impl_.xwalk_local_index_ = value;
}
inline void XClientAddress::set_xwalk_local_index(uint32_t value) {
  _internal_set_xwalk_local_index(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XClientAddress.xwalk_local_index)
}

// uint32 module_type = 4;
inline void XClientAddress::clear_module_type() {
  _impl_.module_type_ = 0u;
}
inline uint32_t XClientAddress::_internal_module_type() const {
  return _impl_.module_type_;
}
inline uint32_t XClientAddress::module_type() const {
  // @@protoc_insertion_point(field_get:xwalk.iw.v1.XClientAddress.module_type)
  return _internal_module_type();
}
inline void XClientAddress::_internal_set_module_type(uint32_t value) {

  _impl_.module_type_ = value;
}
inline void XClientAddress::set_module_type(uint32_t value) {
  _internal_set_module_type(value);
  // @@protoc_insertion_point(field_set:xwalk.iw.v1.XClientAddress.module_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace iw
}  // namespace xwalk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkI2cOperation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkI2cOperation>() {
  return ::xwalk::iw::v1::XWalkI2cOperation_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkSoundOperation> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkSoundOperation>() {
  return ::xwalk::iw::v1::XWalkSoundOperation_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkLifecycleAction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkLifecycleAction>() {
  return ::xwalk::iw::v1::XWalkLifecycleAction_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkMoveAction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkMoveAction>() {
  return ::xwalk::iw::v1::XWalkMoveAction_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkTurnDirection> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkTurnDirection>() {
  return ::xwalk::iw::v1::XWalkTurnDirection_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkCameraAxis> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkCameraAxis>() {
  return ::xwalk::iw::v1::XWalkCameraAxis_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkSensorType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkSensorType>() {
  return ::xwalk::iw::v1::XWalkSensorType_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkCalibrationMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkCalibrationMode>() {
  return ::xwalk::iw::v1::XWalkCalibrationMode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwMessageCmn_2eproto
