// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwSignal.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwSignal_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwSignal_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xHal_5fRpi5CarXIwSignal_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_xHal_5fRpi5CarXIwSignal_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace xwalk {
namespace iw {
namespace v1 {

enum XWalkSignalNumber : int {
  CXX_XWALK_SIGNAL_UNSPECIFIED = 0,
  CXX_XWALK_I2C_REQ = 4225,
  CXX_XWALK_APP_CFG_REQ = 8321,
  CXX_XWALK_APP_ARGS_REQ = 8322,
  CXX_XWALK_CTRL_CMD_REQ = 8323,
  CXX_XWALK_NO_ARG_REQ = 8324,
  CXX_XWALK_LIFECYCLE_REQ = 8325,
  CXX_XWALK_MOVE_REQ = 8326,
  CXX_XWALK_TURN_REQ = 8327,
  CXX_XWALK_CAMERA_REQ = 8328,
  CXX_XWALK_SENSOR_REQ = 8329,
  CXX_XWALK_SELF_DRIVE_REQ = 8330,
  CXX_XWALK_SPI_REQ = 8331,
  CXX_XWALK_GPT_CAR_REQ = 8332,
  CXX_XWALK_CALIBRATION_REQ = 8333,
  CXX_XWALK_SOUND_REQ = 8334,
  CXX_XWALK_SERVO_CAL_CFG_REQ = 8335,
  CXX_XWALK_CMD_UNKNOWN_REQ = 8192,
  CXX_XWALK_CMD_HELP_REQ = 8193,
  CXX_XWALK_CMD_SPI_REQ = 8194,
  CXX_XWALK_CMD_DOCTOR_REQ = 8195,
  CXX_XWALK_CMD_SERVO_ZEROING_REQ = 8196,
  CXX_XWALK_CMD_COMPUTER_VISION_REQ = 8197,
  CXX_XWALK_CMD_RECORD_VIDEO_REQ = 8198,
  CXX_XWALK_CMD_SOUND_BACKGROUND_MUSIC_REQ = 8199,
  CXX_XWALK_CMD_TEXT_VISION_TALK_REQ = 8200,
  CXX_XWALK_CMD_ONLINE_LLM_TEST_REQ = 8201,
  CXX_XWALK_CMD_MOVE_REQ = 8202,
  CXX_XWALK_CMD_KEYBOARD_CONTROL_REQ = 8203,
  CXX_XWALK_CMD_AVOID_OBSTACLES_REQ = 8204,
  CXX_XWALK_CMD_CLIFF_DETECTION_REQ = 8205,
  CXX_XWALK_CMD_STARE_AT_YOU_REQ = 8206,
  CXX_XWALK_CMD_BULL_FIGHT_REQ = 8207,
  CXX_XWALK_CMD_TREASURE_HUNT_REQ = 8208,
  CXX_XWALK_CMD_VIDEO_CAR_REQ = 8209,
  CXX_XWALK_CMD_APP_CONTROL_REQ = 8210,
  CXX_XWALK_CMD_TURN_REQ = 8211,
  CXX_XWALK_CMD_CAMERA_REQ = 8212,
  CXX_XWALK_CMD_SENSOR_REQ = 8213,
  CXX_XWALK_CMD_LINE_TRACK_REQ = 8214,
  CXX_XWALK_CMD_SELF_DRIVE_REQ = 8215,
  CXX_XWALK_CMD_SOUND_REQ = 8216,
  CXX_XWALK_CMD_VOICE_CHAT_REQ = 8217,
  CXX_XWALK_CMD_VOICE_ACTIVE_CAR_REQ = 8218,
  CXX_XWALK_CMD_GPT_CAR_REQ = 8219,
  CXX_XWALK_CMD_VOICE_CONTROLLED_CAR_REQ = 8220,
  CXX_XWALK_CMD_VOICE_PROMPT_CAR_REQ = 8221,
  CXX_XWALK_CMD_STORYTELLING_ROBOT_REQ = 8222,
  CXX_XWALK_CMD_CALIBRATE_REQ = 8223,
  CXX_XWALK_CMD_VIDEO_STREAM_REQ = 8224,
  CXX_XWALK_I2C_CFM = 4226,
  CXX_XWALK_CTRL_CMD_CFM = 8579,
  CXX_XWALK_NO_ARG_CFM = 8580,
  CXX_XWALK_LIFECYCLE_CFM = 8581,
  CXX_XWALK_MOVE_CFM = 8582,
  CXX_XWALK_TURN_CFM = 8583,
  CXX_XWALK_CAMERA_CFM = 8584,
  CXX_XWALK_SENSOR_CFM = 8585,
  CXX_XWALK_SELF_DRIVE_CFM = 8586,
  CXX_XWALK_SPI_CFM = 8587,
  CXX_XWALK_GPT_CAR_CFM = 8588,
  CXX_XWALK_CALIBRATION_CFM = 8589,
  CXX_XWALK_SOUND_CFM = 8590,
  CXX_XWALK_CMD_UNKNOWN_CFM = 8448,
  CXX_XWALK_CMD_HELP_CFM = 8449,
  CXX_XWALK_CMD_SPI_CFM = 8450,
  CXX_XWALK_CMD_DOCTOR_CFM = 8451,
  CXX_XWALK_CMD_SERVO_ZEROING_CFM = 8452,
  CXX_XWALK_CMD_COMPUTER_VISION_CFM = 8453,
  CXX_XWALK_CMD_RECORD_VIDEO_CFM = 8454,
  CXX_XWALK_CMD_SOUND_BACKGROUND_MUSIC_CFM = 8455,
  CXX_XWALK_CMD_TEXT_VISION_TALK_CFM = 8456,
  CXX_XWALK_CMD_ONLINE_LLM_TEST_CFM = 8457,
  CXX_XWALK_CMD_MOVE_CFM = 8458,
  CXX_XWALK_CMD_KEYBOARD_CONTROL_CFM = 8459,
  CXX_XWALK_CMD_AVOID_OBSTACLES_CFM = 8460,
  CXX_XWALK_CMD_CLIFF_DETECTION_CFM = 8461,
  CXX_XWALK_CMD_STARE_AT_YOU_CFM = 8462,
  CXX_XWALK_CMD_BULL_FIGHT_CFM = 8463,
  CXX_XWALK_CMD_TREASURE_HUNT_CFM = 8464,
  CXX_XWALK_CMD_VIDEO_CAR_CFM = 8465,
  CXX_XWALK_CMD_APP_CONTROL_CFM = 8466,
  CXX_XWALK_CMD_TURN_CFM = 8467,
  CXX_XWALK_CMD_CAMERA_CFM = 8468,
  CXX_XWALK_CMD_SENSOR_CFM = 8469,
  CXX_XWALK_CMD_LINE_TRACK_CFM = 8470,
  CXX_XWALK_CMD_SELF_DRIVE_CFM = 8471,
  CXX_XWALK_CMD_SOUND_CFM = 8472,
  CXX_XWALK_CMD_VOICE_CHAT_CFM = 8473,
  CXX_XWALK_CMD_VOICE_ACTIVE_CAR_CFM = 8474,
  CXX_XWALK_CMD_GPT_CAR_CFM = 8475,
  CXX_XWALK_CMD_VOICE_CONTROLLED_CAR_CFM = 8476,
  CXX_XWALK_CMD_VOICE_PROMPT_CAR_CFM = 8477,
  CXX_XWALK_CMD_STORYTELLING_ROBOT_CFM = 8478,
  CXX_XWALK_CMD_CALIBRATE_CFM = 8479,
  CXX_XWALK_CMD_VIDEO_STREAM_CFM = 8480,
  CXX_XWALK_I2C_REJ = 4227,
  CXX_XWALK_CTRL_CMD_REJ = 8835,
  CXX_XWALK_NO_ARG_REJ = 8836,
  CXX_XWALK_LIFECYCLE_REJ = 8837,
  CXX_XWALK_MOVE_REJ = 8838,
  CXX_XWALK_TURN_REJ = 8839,
  CXX_XWALK_CAMERA_REJ = 8840,
  CXX_XWALK_SENSOR_REJ = 8841,
  CXX_XWALK_SELF_DRIVE_REJ = 8842,
  CXX_XWALK_SPI_REJ = 8843,
  CXX_XWALK_GPT_CAR_REJ = 8844,
  CXX_XWALK_CALIBRATION_REJ = 8845,
  CXX_XWALK_SOUND_REJ = 8846,
  CXX_XWALK_CMD_UNKNOWN_REJ = 8704,
  CXX_XWALK_CMD_HELP_REJ = 8705,
  CXX_XWALK_CMD_SPI_REJ = 8706,
  CXX_XWALK_CMD_DOCTOR_REJ = 8707,
  CXX_XWALK_CMD_SERVO_ZEROING_REJ = 8708,
  CXX_XWALK_CMD_COMPUTER_VISION_REJ = 8709,
  CXX_XWALK_CMD_RECORD_VIDEO_REJ = 8710,
  CXX_XWALK_CMD_SOUND_BACKGROUND_MUSIC_REJ = 8711,
  CXX_XWALK_CMD_TEXT_VISION_TALK_REJ = 8712,
  CXX_XWALK_CMD_ONLINE_LLM_TEST_REJ = 8713,
  CXX_XWALK_CMD_MOVE_REJ = 8714,
  CXX_XWALK_CMD_KEYBOARD_CONTROL_REJ = 8715,
  CXX_XWALK_CMD_AVOID_OBSTACLES_REJ = 8716,
  CXX_XWALK_CMD_CLIFF_DETECTION_REJ = 8717,
  CXX_XWALK_CMD_STARE_AT_YOU_REJ = 8718,
  CXX_XWALK_CMD_BULL_FIGHT_REJ = 8719,
  CXX_XWALK_CMD_TREASURE_HUNT_REJ = 8720,
  CXX_XWALK_CMD_VIDEO_CAR_REJ = 8721,
  CXX_XWALK_CMD_APP_CONTROL_REJ = 8722,
  CXX_XWALK_CMD_TURN_REJ = 8723,
  CXX_XWALK_CMD_CAMERA_REJ = 8724,
  CXX_XWALK_CMD_SENSOR_REJ = 8725,
  CXX_XWALK_CMD_LINE_TRACK_REJ = 8726,
  CXX_XWALK_CMD_SELF_DRIVE_REJ = 8727,
  CXX_XWALK_CMD_SOUND_REJ = 8728,
  CXX_XWALK_CMD_VOICE_CHAT_REJ = 8729,
  CXX_XWALK_CMD_VOICE_ACTIVE_CAR_REJ = 8730,
  CXX_XWALK_CMD_GPT_CAR_REJ = 8731,
  CXX_XWALK_CMD_VOICE_CONTROLLED_CAR_REJ = 8732,
  CXX_XWALK_CMD_VOICE_PROMPT_CAR_REJ = 8733,
  CXX_XWALK_CMD_STORYTELLING_ROBOT_REJ = 8734,
  CXX_XWALK_CMD_CALIBRATE_REJ = 8735,
  CXX_XWALK_CMD_VIDEO_STREAM_REJ = 8736,
  XWalkSignalNumber_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkSignalNumber_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkSignalNumber_IsValid(int value);
constexpr XWalkSignalNumber XWalkSignalNumber_MIN = CXX_XWALK_SIGNAL_UNSPECIFIED;
constexpr XWalkSignalNumber XWalkSignalNumber_MAX = CXX_XWALK_SOUND_REJ;
constexpr int XWalkSignalNumber_ARRAYSIZE = XWalkSignalNumber_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkSignalNumber_descriptor();
template<typename T>
inline const std::string& XWalkSignalNumber_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkSignalNumber>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkSignalNumber_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkSignalNumber_descriptor(), enum_t_value);
}
inline bool XWalkSignalNumber_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkSignalNumber* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkSignalNumber>(
    XWalkSignalNumber_descriptor(), name, value);
}
enum XWalkTraceSeverity : int {
  XWALK_TRACE_SEVERITY_UNSPECIFIED = 0,
  XWALK_TRACE_SEVERITY_ERROR = 1,
  XWALK_TRACE_SEVERITY_WARNING = 2,
  XWalkTraceSeverity_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkTraceSeverity_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkTraceSeverity_IsValid(int value);
constexpr XWalkTraceSeverity XWalkTraceSeverity_MIN = XWALK_TRACE_SEVERITY_UNSPECIFIED;
constexpr XWalkTraceSeverity XWalkTraceSeverity_MAX = XWALK_TRACE_SEVERITY_WARNING;
constexpr int XWalkTraceSeverity_ARRAYSIZE = XWalkTraceSeverity_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkTraceSeverity_descriptor();
template<typename T>
inline const std::string& XWalkTraceSeverity_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkTraceSeverity>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkTraceSeverity_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkTraceSeverity_descriptor(), enum_t_value);
}
inline bool XWalkTraceSeverity_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkTraceSeverity* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkTraceSeverity>(
    XWalkTraceSeverity_descriptor(), name, value);
}
enum XWalkErrorSignalNumber : int {
  XWALK_ERROR_SIGNAL_UNSPECIFIED = 0,
  XWALK_ERROR_SIGNAL_INVALID_ARGUMENT = 1,
  XWALK_ERROR_SIGNAL_OUT_OF_RANGE = 2,
  XWALK_ERROR_SIGNAL_LENGTH_ERROR = 3,
  XWALK_ERROR_SIGNAL_DOMAIN_ERROR = 4,
  XWALK_ERROR_SIGNAL_LOGIC_ERROR = 5,
  XWALK_ERROR_SIGNAL_RUNTIME_ERROR = 6,
  XWALK_ERROR_SIGNAL_OVERFLOW_ERROR = 7,
  XWALK_ERROR_SIGNAL_UNDERFLOW_ERROR = 8,
  XWALK_ERROR_SIGNAL_SYSTEM_ERROR = 9,
  XWALK_ERROR_SIGNAL_BAD_ALLOCATION = 10,
  XWALK_ERROR_SIGNAL_BAD_CAST = 11,
  XWALK_ERROR_SIGNAL_BAD_TYPE_ID = 12,
  XWALK_ERROR_SIGNAL_BAD_FUNCTION_CALL = 13,
  XWALK_ERROR_SIGNAL_BAD_OPTIONAL_ACCESS = 14,
  XWALK_ERROR_SIGNAL_BAD_VARIANT_ACCESS = 15,
  XWALK_ERROR_SIGNAL_BAD_WEAK_POINTER = 16,
  XWALK_ERROR_SIGNAL_STANDARD_EXCEPTION = 17,
  XWALK_ERROR_SIGNAL_ABORT = 18,
  XWALK_ERROR_SIGNAL_FLOATING_POINT = 19,
  XWALK_ERROR_SIGNAL_ILLEGAL_INSTRUCTION = 20,
  XWALK_ERROR_SIGNAL_SEGMENTATION_FAULT = 21,
  XWALK_ERROR_SIGNAL_TERMINATION = 22,
  XWALK_ERROR_SIGNAL_INTERRUPT = 23,
  XWALK_ERROR_SIGNAL_BROKEN_PIPE = 24,
  XWALK_ERROR_SIGNAL_HANGUP = 25,
  XWALK_ERROR_SIGNAL_TRAP = 26,
  XWalkErrorSignalNumber_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XWalkErrorSignalNumber_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XWalkErrorSignalNumber_IsValid(int value);
constexpr XWalkErrorSignalNumber XWalkErrorSignalNumber_MIN = XWALK_ERROR_SIGNAL_UNSPECIFIED;
constexpr XWalkErrorSignalNumber XWalkErrorSignalNumber_MAX = XWALK_ERROR_SIGNAL_TRAP;
constexpr int XWalkErrorSignalNumber_ARRAYSIZE = XWalkErrorSignalNumber_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkErrorSignalNumber_descriptor();
template<typename T>
inline const std::string& XWalkErrorSignalNumber_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XWalkErrorSignalNumber>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XWalkErrorSignalNumber_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XWalkErrorSignalNumber_descriptor(), enum_t_value);
}
inline bool XWalkErrorSignalNumber_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XWalkErrorSignalNumber* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XWalkErrorSignalNumber>(
    XWalkErrorSignalNumber_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace iw
}  // namespace xwalk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkSignalNumber> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkSignalNumber>() {
  return ::xwalk::iw::v1::XWalkSignalNumber_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkTraceSeverity> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkTraceSeverity>() {
  return ::xwalk::iw::v1::XWalkTraceSeverity_descriptor();
}
template <> struct is_proto_enum< ::xwalk::iw::v1::XWalkErrorSignalNumber> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xwalk::iw::v1::XWalkErrorSignalNumber>() {
  return ::xwalk::iw::v1::XWalkErrorSignalNumber_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_xHal_5fRpi5CarXIwSignal_2eproto
