// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwGrpc.proto

#include "xHal_Rpi5CarXIwGrpc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace xwalk {
namespace iw {
namespace v1 {
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_xHal_5fRpi5CarXIwGrpc_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_xHal_5fRpi5CarXIwGrpc_2eproto = nullptr;
const uint32_t TableStruct_xHal_5fRpi5CarXIwGrpc_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_xHal_5fRpi5CarXIwGrpc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031xHal_Rpi5CarXIwGrpc.proto\022\013xwalk.iw.v1"
  "\032\037xHal_Rpi5CarXIwMessageReq.proto\032\037xHal_"
  "Rpi5CarXIwMessageCfm.proto2f\n\023XWalkCtrlI"
  "2cService\022O\n\007Execute\022#.xwalk.iw.v1.XWalk"
  "I2cRequestPayload\032\037.xwalk.iw.v1.XWalkI2c"
  "CfmPayload2\232\006\n\027XWalkCtrlVehicleService\022N"
  "\n\004Move\022$.xwalk.iw.v1.XWalkMoveCommandReq"
  "uest\032 .xwalk.iw.v1.XWalkMoveCommandCfm\022o"
  "\n\017KeyboardControl\022/.xwalk.iw.v1.XWalkKey"
  "boardControlCommandRequest\032+.xwalk.iw.v1"
  ".XWalkKeyboardControlCommandCfm\022l\n\016Avoid"
  "Obstacles\022..xwalk.iw.v1.XWalkAvoidObstac"
  "lesCommandRequest\032*.xwalk.iw.v1.XWalkAvo"
  "idObstaclesCommandCfm\022l\n\016CliffDetection\022"
  "..xwalk.iw.v1.XWalkCliffDetectionCommand"
  "Request\032*.xwalk.iw.v1.XWalkCliffDetectio"
  "nCommandCfm\022N\n\004Turn\022$.xwalk.iw.v1.XWalkT"
  "urnCommandRequest\032 .xwalk.iw.v1.XWalkTur"
  "nCommandCfm\022T\n\006Sensor\022&.xwalk.iw.v1.XWal"
  "kSensorCommandRequest\032\".xwalk.iw.v1.XWal"
  "kSensorCommandCfm\022]\n\tLineTrack\022).xwalk.i"
  "w.v1.XWalkLineTrackCommandRequest\032%.xwal"
  "k.iw.v1.XWalkLineTrackCommandCfm\022]\n\tSelf"
  "Drive\022).xwalk.iw.v1.XWalkSelfDriveComman"
  "dRequest\032%.xwalk.iw.v1.XWalkSelfDriveCom"
  "mandCfm2\253\006\n\026XWalkCtrlVisionService\022l\n\016Co"
  "mputerVision\022..xwalk.iw.v1.XWalkComputer"
  "VisionCommandRequest\032*.xwalk.iw.v1.XWalk"
  "ComputerVisionCommandCfm\022c\n\013RecordVideo\022"
  "+.xwalk.iw.v1.XWalkRecordVideoCommandReq"
  "uest\032\'.xwalk.iw.v1.XWalkRecordVideoComma"
  "ndCfm\022`\n\nStareAtYou\022*.xwalk.iw.v1.XWalkS"
  "tareAtYouCommandRequest\032&.xwalk.iw.v1.XW"
  "alkStareAtYouCommandCfm\022]\n\tBullFight\022).x"
  "walk.iw.v1.XWalkBullFightCommandRequest\032"
  "%.xwalk.iw.v1.XWalkBullFightCommandCfm\022f"
  "\n\014TreasureHunt\022,.xwalk.iw.v1.XWalkTreasu"
  "reHuntCommandRequest\032(.xwalk.iw.v1.XWalk"
  "TreasureHuntCommandCfm\022Z\n\010VideoCar\022(.xwa"
  "lk.iw.v1.XWalkVideoCarCommandRequest\032$.x"
  "walk.iw.v1.XWalkVideoCarCommandCfm\022c\n\013Vi"
  "deoStream\022+.xwalk.iw.v1.XWalkVideoStream"
  "CommandRequest\032\'.xwalk.iw.v1.XWalkVideoS"
  "treamCommandCfm\022T\n\006Camera\022&.xwalk.iw.v1."
  "XWalkCameraCommandRequest\032\".xwalk.iw.v1."
  "XWalkCameraCommandCfm2\362\006\n\025XWalkCtrlVoice"
  "Service\022l\n\016TextVisionTalk\022..xwalk.iw.v1."
  "XWalkTextVisionTalkCommandRequest\032*.xwal"
  "k.iw.v1.XWalkTextVisionTalkCommandCfm\022i\n"
  "\rOnlineLlmTest\022-.xwalk.iw.v1.XWalkOnline"
  "LlmTestCommandRequest\032).xwalk.iw.v1.XWal"
  "kOnlineLlmTestCommandCfm\022]\n\tVoiceChat\022)."
  "xwalk.iw.v1.XWalkVoiceChatCommandRequest"
  "\032%.xwalk.iw.v1.XWalkVoiceChatCommandCfm\022"
  "l\n\016VoiceActiveCar\022..xwalk.iw.v1.XWalkVoi"
  "ceActiveCarCommandRequest\032*.xwalk.iw.v1."
  "XWalkVoiceActiveCarCommandCfm\022T\n\006GptCar\022"
  "&.xwalk.iw.v1.XWalkGptCarCommandRequest\032"
  "\".xwalk.iw.v1.XWalkGptCarCommandCfm\022x\n\022V"
  "oiceControlledCar\0222.xwalk.iw.v1.XWalkVoi"
  "ceControlledCarCommandRequest\032..xwalk.iw"
  ".v1.XWalkVoiceControlledCarCommandCfm\022l\n"
  "\016VoicePromptCar\022..xwalk.iw.v1.XWalkVoice"
  "PromptCarCommandRequest\032*.xwalk.iw.v1.XW"
  "alkVoicePromptCarCommandCfm\022u\n\021Storytell"
  "ingRobot\0221.xwalk.iw.v1.XWalkStorytelling"
  "RobotCommandRequest\032-.xwalk.iw.v1.XWalkS"
  "torytellingRobotCommandCfm2\352\001\n\025XWalkCtrl"
  "MediaService\022~\n\024SoundBackgroundMusic\0224.x"
  "walk.iw.v1.XWalkSoundBackgroundMusicComm"
  "andRequest\0320.xwalk.iw.v1.XWalkSoundBackg"
  "roundMusicCommandCfm\022Q\n\005Sound\022%.xwalk.iw"
  ".v1.XWalkSoundCommandRequest\032!.xwalk.iw."
  "v1.XWalkSoundCommandCfm2\315\001\n\034XWalkCtrlCon"
  "nectivityService\022K\n\003Spi\022#.xwalk.iw.v1.XW"
  "alkSpiCommandRequest\032\037.xwalk.iw.v1.XWalk"
  "SpiCommandCfm\022`\n\nAppControl\022*.xwalk.iw.v"
  "1.XWalkAppControlCommandRequest\032&.xwalk."
  "iw.v1.XWalkAppControlCommandCfm2\344\001\n\033XWal"
  "kCtrlCalibrationService\022f\n\014ServoZeroing\022"
  ",.xwalk.iw.v1.XWalkServoZeroingCommandRe"
  "quest\032(.xwalk.iw.v1.XWalkServoZeroingCom"
  "mandCfm\022]\n\tCalibrate\022).xwalk.iw.v1.XWalk"
  "CalibrateCommandRequest\032%.xwalk.iw.v1.XW"
  "alkCalibrateCommandCfm2\231\002\n\030XWalkCtrlPlat"
  "formService\022W\n\007Unknown\022\'.xwalk.iw.v1.XWa"
  "lkUnknownCommandRequest\032#.xwalk.iw.v1.XW"
  "alkUnknownCommandCfm\022N\n\004Help\022$.xwalk.iw."
  "v1.XWalkHelpCommandRequest\032 .xwalk.iw.v1"
  ".XWalkHelpCommandCfm\022T\n\006Doctor\022&.xwalk.i"
  "w.v1.XWalkDoctorCommandRequest\032\".xwalk.i"
  "w.v1.XWalkDoctorCommandCfmb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_xHal_5fRpi5CarXIwGrpc_2eproto_deps[2] = {
  &::descriptor_table_xHal_5fRpi5CarXIwMessageCfm_2eproto,
  &::descriptor_table_xHal_5fRpi5CarXIwMessageReq_2eproto,
};
static ::_pbi::once_flag descriptor_table_xHal_5fRpi5CarXIwGrpc_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwGrpc_2eproto = {
    false, false, 3674, descriptor_table_protodef_xHal_5fRpi5CarXIwGrpc_2eproto,
    "xHal_Rpi5CarXIwGrpc.proto",
    &descriptor_table_xHal_5fRpi5CarXIwGrpc_2eproto_once, descriptor_table_xHal_5fRpi5CarXIwGrpc_2eproto_deps, 2, 0,
    schemas, file_default_instances, TableStruct_xHal_5fRpi5CarXIwGrpc_2eproto::offsets,
    nullptr, file_level_enum_descriptors_xHal_5fRpi5CarXIwGrpc_2eproto,
    file_level_service_descriptors_xHal_5fRpi5CarXIwGrpc_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xHal_5fRpi5CarXIwGrpc_2eproto_getter() {
  return &descriptor_table_xHal_5fRpi5CarXIwGrpc_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xHal_5fRpi5CarXIwGrpc_2eproto(&descriptor_table_xHal_5fRpi5CarXIwGrpc_2eproto);
namespace xwalk {
namespace iw {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
