// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwSignal.proto

#include "xHal_Rpi5CarXIwSignal.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace xwalk {
namespace iw {
namespace v1 {
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_xHal_5fRpi5CarXIwSignal_2eproto[3];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_xHal_5fRpi5CarXIwSignal_2eproto = nullptr;
const uint32_t TableStruct_xHal_5fRpi5CarXIwSignal_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_xHal_5fRpi5CarXIwSignal_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033xHal_Rpi5CarXIwSignal.proto\022\013xwalk.iw."
  "v1*\261%\n\021XWalkSignalNumber\022 \n\034CXX_XWALK_SI"
  "GNAL_UNSPECIFIED\020\000\022\026\n\021CXX_XWALK_I2C_REQ\020"
  "\201!\022\032\n\025CXX_XWALK_APP_CFG_REQ\020\201A\022\033\n\026CXX_XW"
  "ALK_APP_ARGS_REQ\020\202A\022\033\n\026CXX_XWALK_CTRL_CM"
  "D_REQ\020\203A\022\031\n\024CXX_XWALK_NO_ARG_REQ\020\204A\022\034\n\027C"
  "XX_XWALK_LIFECYCLE_REQ\020\205A\022\027\n\022CXX_XWALK_M"
  "OVE_REQ\020\206A\022\027\n\022CXX_XWALK_TURN_REQ\020\207A\022\031\n\024C"
  "XX_XWALK_CAMERA_REQ\020\210A\022\031\n\024CXX_XWALK_SENS"
  "OR_REQ\020\211A\022\035\n\030CXX_XWALK_SELF_DRIVE_REQ\020\212A"
  "\022\026\n\021CXX_XWALK_SPI_REQ\020\213A\022\032\n\025CXX_XWALK_GP"
  "T_CAR_REQ\020\214A\022\036\n\031CXX_XWALK_CALIBRATION_RE"
  "Q\020\215A\022\030\n\023CXX_XWALK_SOUND_REQ\020\216A\022 \n\033CXX_XW"
  "ALK_SERVO_CAL_CFG_REQ\020\217A\022\036\n\031CXX_XWALK_CM"
  "D_UNKNOWN_REQ\020\200@\022\033\n\026CXX_XWALK_CMD_HELP_R"
  "EQ\020\201@\022\032\n\025CXX_XWALK_CMD_SPI_REQ\020\202@\022\035\n\030CXX"
  "_XWALK_CMD_DOCTOR_REQ\020\203@\022$\n\037CXX_XWALK_CM"
  "D_SERVO_ZEROING_REQ\020\204@\022&\n!CXX_XWALK_CMD_"
  "COMPUTER_VISION_REQ\020\205@\022#\n\036CXX_XWALK_CMD_"
  "RECORD_VIDEO_REQ\020\206@\022-\n(CXX_XWALK_CMD_SOU"
  "ND_BACKGROUND_MUSIC_REQ\020\207@\022\'\n\"CXX_XWALK_"
  "CMD_TEXT_VISION_TALK_REQ\020\210@\022&\n!CXX_XWALK"
  "_CMD_ONLINE_LLM_TEST_REQ\020\211@\022\033\n\026CXX_XWALK"
  "_CMD_MOVE_REQ\020\212@\022\'\n\"CXX_XWALK_CMD_KEYBOA"
  "RD_CONTROL_REQ\020\213@\022&\n!CXX_XWALK_CMD_AVOID"
  "_OBSTACLES_REQ\020\214@\022&\n!CXX_XWALK_CMD_CLIFF"
  "_DETECTION_REQ\020\215@\022#\n\036CXX_XWALK_CMD_STARE"
  "_AT_YOU_REQ\020\216@\022!\n\034CXX_XWALK_CMD_BULL_FIG"
  "HT_REQ\020\217@\022$\n\037CXX_XWALK_CMD_TREASURE_HUNT"
  "_REQ\020\220@\022 \n\033CXX_XWALK_CMD_VIDEO_CAR_REQ\020\221"
  "@\022\"\n\035CXX_XWALK_CMD_APP_CONTROL_REQ\020\222@\022\033\n"
  "\026CXX_XWALK_CMD_TURN_REQ\020\223@\022\035\n\030CXX_XWALK_"
  "CMD_CAMERA_REQ\020\224@\022\035\n\030CXX_XWALK_CMD_SENSO"
  "R_REQ\020\225@\022!\n\034CXX_XWALK_CMD_LINE_TRACK_REQ"
  "\020\226@\022!\n\034CXX_XWALK_CMD_SELF_DRIVE_REQ\020\227@\022\034"
  "\n\027CXX_XWALK_CMD_SOUND_REQ\020\230@\022!\n\034CXX_XWAL"
  "K_CMD_VOICE_CHAT_REQ\020\231@\022\'\n\"CXX_XWALK_CMD"
  "_VOICE_ACTIVE_CAR_REQ\020\232@\022\036\n\031CXX_XWALK_CM"
  "D_GPT_CAR_REQ\020\233@\022+\n&CXX_XWALK_CMD_VOICE_"
  "CONTROLLED_CAR_REQ\020\234@\022\'\n\"CXX_XWALK_CMD_V"
  "OICE_PROMPT_CAR_REQ\020\235@\022)\n$CXX_XWALK_CMD_"
  "STORYTELLING_ROBOT_REQ\020\236@\022 \n\033CXX_XWALK_C"
  "MD_CALIBRATE_REQ\020\237@\022#\n\036CXX_XWALK_CMD_VID"
  "EO_STREAM_REQ\020\240@\022\026\n\021CXX_XWALK_I2C_CFM\020\202!"
  "\022\033\n\026CXX_XWALK_CTRL_CMD_CFM\020\203C\022\031\n\024CXX_XWA"
  "LK_NO_ARG_CFM\020\204C\022\034\n\027CXX_XWALK_LIFECYCLE_"
  "CFM\020\205C\022\027\n\022CXX_XWALK_MOVE_CFM\020\206C\022\027\n\022CXX_X"
  "WALK_TURN_CFM\020\207C\022\031\n\024CXX_XWALK_CAMERA_CFM"
  "\020\210C\022\031\n\024CXX_XWALK_SENSOR_CFM\020\211C\022\035\n\030CXX_XW"
  "ALK_SELF_DRIVE_CFM\020\212C\022\026\n\021CXX_XWALK_SPI_C"
  "FM\020\213C\022\032\n\025CXX_XWALK_GPT_CAR_CFM\020\214C\022\036\n\031CXX"
  "_XWALK_CALIBRATION_CFM\020\215C\022\030\n\023CXX_XWALK_S"
  "OUND_CFM\020\216C\022\036\n\031CXX_XWALK_CMD_UNKNOWN_CFM"
  "\020\200B\022\033\n\026CXX_XWALK_CMD_HELP_CFM\020\201B\022\032\n\025CXX_"
  "XWALK_CMD_SPI_CFM\020\202B\022\035\n\030CXX_XWALK_CMD_DO"
  "CTOR_CFM\020\203B\022$\n\037CXX_XWALK_CMD_SERVO_ZEROI"
  "NG_CFM\020\204B\022&\n!CXX_XWALK_CMD_COMPUTER_VISI"
  "ON_CFM\020\205B\022#\n\036CXX_XWALK_CMD_RECORD_VIDEO_"
  "CFM\020\206B\022-\n(CXX_XWALK_CMD_SOUND_BACKGROUND"
  "_MUSIC_CFM\020\207B\022\'\n\"CXX_XWALK_CMD_TEXT_VISI"
  "ON_TALK_CFM\020\210B\022&\n!CXX_XWALK_CMD_ONLINE_L"
  "LM_TEST_CFM\020\211B\022\033\n\026CXX_XWALK_CMD_MOVE_CFM"
  "\020\212B\022\'\n\"CXX_XWALK_CMD_KEYBOARD_CONTROL_CF"
  "M\020\213B\022&\n!CXX_XWALK_CMD_AVOID_OBSTACLES_CF"
  "M\020\214B\022&\n!CXX_XWALK_CMD_CLIFF_DETECTION_CF"
  "M\020\215B\022#\n\036CXX_XWALK_CMD_STARE_AT_YOU_CFM\020\216"
  "B\022!\n\034CXX_XWALK_CMD_BULL_FIGHT_CFM\020\217B\022$\n\037"
  "CXX_XWALK_CMD_TREASURE_HUNT_CFM\020\220B\022 \n\033CX"
  "X_XWALK_CMD_VIDEO_CAR_CFM\020\221B\022\"\n\035CXX_XWAL"
  "K_CMD_APP_CONTROL_CFM\020\222B\022\033\n\026CXX_XWALK_CM"
  "D_TURN_CFM\020\223B\022\035\n\030CXX_XWALK_CMD_CAMERA_CF"
  "M\020\224B\022\035\n\030CXX_XWALK_CMD_SENSOR_CFM\020\225B\022!\n\034C"
  "XX_XWALK_CMD_LINE_TRACK_CFM\020\226B\022!\n\034CXX_XW"
  "ALK_CMD_SELF_DRIVE_CFM\020\227B\022\034\n\027CXX_XWALK_C"
  "MD_SOUND_CFM\020\230B\022!\n\034CXX_XWALK_CMD_VOICE_C"
  "HAT_CFM\020\231B\022\'\n\"CXX_XWALK_CMD_VOICE_ACTIVE"
  "_CAR_CFM\020\232B\022\036\n\031CXX_XWALK_CMD_GPT_CAR_CFM"
  "\020\233B\022+\n&CXX_XWALK_CMD_VOICE_CONTROLLED_CA"
  "R_CFM\020\234B\022\'\n\"CXX_XWALK_CMD_VOICE_PROMPT_C"
  "AR_CFM\020\235B\022)\n$CXX_XWALK_CMD_STORYTELLING_"
  "ROBOT_CFM\020\236B\022 \n\033CXX_XWALK_CMD_CALIBRATE_"
  "CFM\020\237B\022#\n\036CXX_XWALK_CMD_VIDEO_STREAM_CFM"
  "\020\240B\022\026\n\021CXX_XWALK_I2C_REJ\020\203!\022\033\n\026CXX_XWALK"
  "_CTRL_CMD_REJ\020\203E\022\031\n\024CXX_XWALK_NO_ARG_REJ"
  "\020\204E\022\034\n\027CXX_XWALK_LIFECYCLE_REJ\020\205E\022\027\n\022CXX"
  "_XWALK_MOVE_REJ\020\206E\022\027\n\022CXX_XWALK_TURN_REJ"
  "\020\207E\022\031\n\024CXX_XWALK_CAMERA_REJ\020\210E\022\031\n\024CXX_XW"
  "ALK_SENSOR_REJ\020\211E\022\035\n\030CXX_XWALK_SELF_DRIV"
  "E_REJ\020\212E\022\026\n\021CXX_XWALK_SPI_REJ\020\213E\022\032\n\025CXX_"
  "XWALK_GPT_CAR_REJ\020\214E\022\036\n\031CXX_XWALK_CALIBR"
  "ATION_REJ\020\215E\022\030\n\023CXX_XWALK_SOUND_REJ\020\216E\022\036"
  "\n\031CXX_XWALK_CMD_UNKNOWN_REJ\020\200D\022\033\n\026CXX_XW"
  "ALK_CMD_HELP_REJ\020\201D\022\032\n\025CXX_XWALK_CMD_SPI"
  "_REJ\020\202D\022\035\n\030CXX_XWALK_CMD_DOCTOR_REJ\020\203D\022$"
  "\n\037CXX_XWALK_CMD_SERVO_ZEROING_REJ\020\204D\022&\n!"
  "CXX_XWALK_CMD_COMPUTER_VISION_REJ\020\205D\022#\n\036"
  "CXX_XWALK_CMD_RECORD_VIDEO_REJ\020\206D\022-\n(CXX"
  "_XWALK_CMD_SOUND_BACKGROUND_MUSIC_REJ\020\207D"
  "\022\'\n\"CXX_XWALK_CMD_TEXT_VISION_TALK_REJ\020\210"
  "D\022&\n!CXX_XWALK_CMD_ONLINE_LLM_TEST_REJ\020\211"
  "D\022\033\n\026CXX_XWALK_CMD_MOVE_REJ\020\212D\022\'\n\"CXX_XW"
  "ALK_CMD_KEYBOARD_CONTROL_REJ\020\213D\022&\n!CXX_X"
  "WALK_CMD_AVOID_OBSTACLES_REJ\020\214D\022&\n!CXX_X"
  "WALK_CMD_CLIFF_DETECTION_REJ\020\215D\022#\n\036CXX_X"
  "WALK_CMD_STARE_AT_YOU_REJ\020\216D\022!\n\034CXX_XWAL"
  "K_CMD_BULL_FIGHT_REJ\020\217D\022$\n\037CXX_XWALK_CMD"
  "_TREASURE_HUNT_REJ\020\220D\022 \n\033CXX_XWALK_CMD_V"
  "IDEO_CAR_REJ\020\221D\022\"\n\035CXX_XWALK_CMD_APP_CON"
  "TROL_REJ\020\222D\022\033\n\026CXX_XWALK_CMD_TURN_REJ\020\223D"
  "\022\035\n\030CXX_XWALK_CMD_CAMERA_REJ\020\224D\022\035\n\030CXX_X"
  "WALK_CMD_SENSOR_REJ\020\225D\022!\n\034CXX_XWALK_CMD_"
  "LINE_TRACK_REJ\020\226D\022!\n\034CXX_XWALK_CMD_SELF_"
  "DRIVE_REJ\020\227D\022\034\n\027CXX_XWALK_CMD_SOUND_REJ\020"
  "\230D\022!\n\034CXX_XWALK_CMD_VOICE_CHAT_REJ\020\231D\022\'\n"
  "\"CXX_XWALK_CMD_VOICE_ACTIVE_CAR_REJ\020\232D\022\036"
  "\n\031CXX_XWALK_CMD_GPT_CAR_REJ\020\233D\022+\n&CXX_XW"
  "ALK_CMD_VOICE_CONTROLLED_CAR_REJ\020\234D\022\'\n\"C"
  "XX_XWALK_CMD_VOICE_PROMPT_CAR_REJ\020\235D\022)\n$"
  "CXX_XWALK_CMD_STORYTELLING_ROBOT_REJ\020\236D\022"
  " \n\033CXX_XWALK_CMD_CALIBRATE_REJ\020\237D\022#\n\036CXX"
  "_XWALK_CMD_VIDEO_STREAM_REJ\020\240D*|\n\022XWalkT"
  "raceSeverity\022$\n XWALK_TRACE_SEVERITY_UNS"
  "PECIFIED\020\000\022\036\n\032XWALK_TRACE_SEVERITY_ERROR"
  "\020\001\022 \n\034XWALK_TRACE_SEVERITY_WARNING\020\002*\225\010\n"
  "\026XWalkErrorSignalNumber\022\"\n\036XWALK_ERROR_S"
  "IGNAL_UNSPECIFIED\020\000\022\'\n#XWALK_ERROR_SIGNA"
  "L_INVALID_ARGUMENT\020\001\022#\n\037XWALK_ERROR_SIGN"
  "AL_OUT_OF_RANGE\020\002\022#\n\037XWALK_ERROR_SIGNAL_"
  "LENGTH_ERROR\020\003\022#\n\037XWALK_ERROR_SIGNAL_DOM"
  "AIN_ERROR\020\004\022\"\n\036XWALK_ERROR_SIGNAL_LOGIC_"
  "ERROR\020\005\022$\n XWALK_ERROR_SIGNAL_RUNTIME_ER"
  "ROR\020\006\022%\n!XWALK_ERROR_SIGNAL_OVERFLOW_ERR"
  "OR\020\007\022&\n\"XWALK_ERROR_SIGNAL_UNDERFLOW_ERR"
  "OR\020\010\022#\n\037XWALK_ERROR_SIGNAL_SYSTEM_ERROR\020"
  "\t\022%\n!XWALK_ERROR_SIGNAL_BAD_ALLOCATION\020\n"
  "\022\037\n\033XWALK_ERROR_SIGNAL_BAD_CAST\020\013\022\"\n\036XWA"
  "LK_ERROR_SIGNAL_BAD_TYPE_ID\020\014\022(\n$XWALK_E"
  "RROR_SIGNAL_BAD_FUNCTION_CALL\020\r\022*\n&XWALK"
  "_ERROR_SIGNAL_BAD_OPTIONAL_ACCESS\020\016\022)\n%X"
  "WALK_ERROR_SIGNAL_BAD_VARIANT_ACCESS\020\017\022\'"
  "\n#XWALK_ERROR_SIGNAL_BAD_WEAK_POINTER\020\020\022"
  ")\n%XWALK_ERROR_SIGNAL_STANDARD_EXCEPTION"
  "\020\021\022\034\n\030XWALK_ERROR_SIGNAL_ABORT\020\022\022%\n!XWAL"
  "K_ERROR_SIGNAL_FLOATING_POINT\020\023\022*\n&XWALK"
  "_ERROR_SIGNAL_ILLEGAL_INSTRUCTION\020\024\022)\n%X"
  "WALK_ERROR_SIGNAL_SEGMENTATION_FAULT\020\025\022\""
  "\n\036XWALK_ERROR_SIGNAL_TERMINATION\020\026\022 \n\034XW"
  "ALK_ERROR_SIGNAL_INTERRUPT\020\027\022\"\n\036XWALK_ER"
  "ROR_SIGNAL_BROKEN_PIPE\020\030\022\035\n\031XWALK_ERROR_"
  "SIGNAL_HANGUP\020\031\022\033\n\027XWALK_ERROR_SIGNAL_TR"
  "AP\020\032b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto = {
    false, false, 6012, descriptor_table_protodef_xHal_5fRpi5CarXIwSignal_2eproto,
    "xHal_Rpi5CarXIwSignal.proto",
    &descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_xHal_5fRpi5CarXIwSignal_2eproto::offsets,
    nullptr, file_level_enum_descriptors_xHal_5fRpi5CarXIwSignal_2eproto,
    file_level_service_descriptors_xHal_5fRpi5CarXIwSignal_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto_getter() {
  return &descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xHal_5fRpi5CarXIwSignal_2eproto(&descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto);
namespace xwalk {
namespace iw {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkSignalNumber_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwSignal_2eproto[0];
}
bool XWalkSignalNumber_IsValid(int value) {
  switch (value) {
    case 0:
    case 4225:
    case 4226:
    case 4227:
    case 8192:
    case 8193:
    case 8194:
    case 8195:
    case 8196:
    case 8197:
    case 8198:
    case 8199:
    case 8200:
    case 8201:
    case 8202:
    case 8203:
    case 8204:
    case 8205:
    case 8206:
    case 8207:
    case 8208:
    case 8209:
    case 8210:
    case 8211:
    case 8212:
    case 8213:
    case 8214:
    case 8215:
    case 8216:
    case 8217:
    case 8218:
    case 8219:
    case 8220:
    case 8221:
    case 8222:
    case 8223:
    case 8224:
    case 8321:
    case 8322:
    case 8323:
    case 8324:
    case 8325:
    case 8326:
    case 8327:
    case 8328:
    case 8329:
    case 8330:
    case 8331:
    case 8332:
    case 8333:
    case 8334:
    case 8335:
    case 8448:
    case 8449:
    case 8450:
    case 8451:
    case 8452:
    case 8453:
    case 8454:
    case 8455:
    case 8456:
    case 8457:
    case 8458:
    case 8459:
    case 8460:
    case 8461:
    case 8462:
    case 8463:
    case 8464:
    case 8465:
    case 8466:
    case 8467:
    case 8468:
    case 8469:
    case 8470:
    case 8471:
    case 8472:
    case 8473:
    case 8474:
    case 8475:
    case 8476:
    case 8477:
    case 8478:
    case 8479:
    case 8480:
    case 8579:
    case 8580:
    case 8581:
    case 8582:
    case 8583:
    case 8584:
    case 8585:
    case 8586:
    case 8587:
    case 8588:
    case 8589:
    case 8590:
    case 8704:
    case 8705:
    case 8706:
    case 8707:
    case 8708:
    case 8709:
    case 8710:
    case 8711:
    case 8712:
    case 8713:
    case 8714:
    case 8715:
    case 8716:
    case 8717:
    case 8718:
    case 8719:
    case 8720:
    case 8721:
    case 8722:
    case 8723:
    case 8724:
    case 8725:
    case 8726:
    case 8727:
    case 8728:
    case 8729:
    case 8730:
    case 8731:
    case 8732:
    case 8733:
    case 8734:
    case 8735:
    case 8736:
    case 8835:
    case 8836:
    case 8837:
    case 8838:
    case 8839:
    case 8840:
    case 8841:
    case 8842:
    case 8843:
    case 8844:
    case 8845:
    case 8846:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkTraceSeverity_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwSignal_2eproto[1];
}
bool XWalkTraceSeverity_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkErrorSignalNumber_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwSignal_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwSignal_2eproto[2];
}
bool XWalkErrorSignalNumber_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
