// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xHal_Rpi5CarXIwMessageCmn.proto

#include "xHal_Rpi5CarXIwMessageCmn.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace xwalk {
namespace iw {
namespace v1 {
PROTOBUF_CONSTEXPR XClientAddress::XClientAddress(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.client_address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.mail_box_id_)*/0u
  , /*decltype(_impl_.xwalk_local_index_)*/0u
  , /*decltype(_impl_.module_type_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XClientAddressDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XClientAddressDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XClientAddressDefaultTypeInternal() {}
  union {
    XClientAddress _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XClientAddressDefaultTypeInternal _XClientAddress_default_instance_;
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
static ::_pb::Metadata file_level_metadata_xHal_5fRpi5CarXIwMessageCmn_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[8];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto = nullptr;

const uint32_t TableStruct_xHal_5fRpi5CarXIwMessageCmn_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XClientAddress, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XClientAddress, _impl_.mail_box_id_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XClientAddress, _impl_.client_address_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XClientAddress, _impl_.xwalk_local_index_),
  PROTOBUF_FIELD_OFFSET(::xwalk::iw::v1::XClientAddress, _impl_.module_type_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::xwalk::iw::v1::XClientAddress)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::xwalk::iw::v1::_XClientAddress_default_instance_._instance,
};

const char descriptor_table_protodef_xHal_5fRpi5CarXIwMessageCmn_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037xHal_Rpi5CarXIwMessageCmn.proto\022\013xwalk"
  ".iw.v1\"m\n\016XClientAddress\022\023\n\013mail_box_id\030"
  "\001 \001(\r\022\026\n\016client_address\030\002 \001(\t\022\031\n\021xwalk_l"
  "ocal_index\030\003 \001(\r\022\023\n\013module_type\030\004 \001(\r*\304\001"
  "\n\021XWalkI2cOperation\022#\n\037XWALK_I2C_OPERATI"
  "ON_UNSPECIFIED\020\000\022\035\n\031XWALK_I2C_OPERATION_"
  "PROBE\020\001\022\034\n\030XWALK_I2C_OPERATION_READ\020\002\022%\n"
  "!XWALK_I2C_OPERATION_READ_REGISTER\020\003\022&\n\""
  "XWALK_I2C_OPERATION_WRITE_REGISTER\020\004*\230\001\n"
  "\023XWalkSoundOperation\022\036\n\032XWALK_SOUND_OPER"
  "ATION_PLAY\020\000\022 \n\034XWALK_SOUND_OPERATION_VO"
  "LUME\020\001\022\037\n\033XWALK_SOUND_OPERATION_MUSIC\020\002\022"
  "\036\n\032XWALK_SOUND_OPERATION_STOP\020\003*Y\n\024XWalk"
  "LifecycleAction\022 \n\034XWALK_LIFECYCLE_ACTIO"
  "N_START\020\000\022\037\n\033XWALK_LIFECYCLE_ACTION_STOP"
  "\020\001*l\n\017XWalkMoveAction\022\035\n\031XWALK_MOVE_ACTI"
  "ON_FORWARD\020\000\022\036\n\032XWALK_MOVE_ACTION_BACKWA"
  "RD\020\001\022\032\n\026XWALK_MOVE_ACTION_DEMO\020\002*S\n\022XWal"
  "kTurnDirection\022\035\n\031XWALK_TURN_DIRECTION_L"
  "EFT\020\000\022\036\n\032XWALK_TURN_DIRECTION_RIGHT\020\001*H\n"
  "\017XWalkCameraAxis\022\031\n\025XWALK_CAMERA_AXIS_PA"
  "N\020\000\022\032\n\026XWALK_CAMERA_AXIS_TILT\020\001*R\n\017XWalk"
  "SensorType\022\036\n\032XWALK_SENSOR_TYPE_DISTANCE"
  "\020\000\022\037\n\033XWALK_SENSOR_TYPE_GRAYSCALE\020\001*\211\001\n\024"
  "XWalkCalibrationMode\022#\n\037XWALK_CALIBRATIO"
  "N_MODE_COMPLETE\020\000\022$\n XWALK_CALIBRATION_M"
  "ODE_GRAYSCALE\020\001\022&\n\"XWALK_CALIBRATION_MOD"
  "E_SERVO_MOTOR\020\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto = {
    false, false, 1103, descriptor_table_protodef_xHal_5fRpi5CarXIwMessageCmn_2eproto,
    "xHal_Rpi5CarXIwMessageCmn.proto",
    &descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_xHal_5fRpi5CarXIwMessageCmn_2eproto::offsets,
    file_level_metadata_xHal_5fRpi5CarXIwMessageCmn_2eproto, file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto,
    file_level_service_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto_getter() {
  return &descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xHal_5fRpi5CarXIwMessageCmn_2eproto(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
namespace xwalk {
namespace iw {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkI2cOperation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[0];
}
bool XWalkI2cOperation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkSoundOperation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[1];
}
bool XWalkSoundOperation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkLifecycleAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[2];
}
bool XWalkLifecycleAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkMoveAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[3];
}
bool XWalkMoveAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkTurnDirection_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[4];
}
bool XWalkTurnDirection_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkCameraAxis_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[5];
}
bool XWalkCameraAxis_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkSensorType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[6];
}
bool XWalkSensorType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XWalkCalibrationMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto);
  return file_level_enum_descriptors_xHal_5fRpi5CarXIwMessageCmn_2eproto[7];
}
bool XWalkCalibrationMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class XClientAddress::_Internal {
 public:
};

XClientAddress::XClientAddress(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xwalk.iw.v1.XClientAddress)
}
XClientAddress::XClientAddress(const XClientAddress& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XClientAddress* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.client_address_){}
    , decltype(_impl_.mail_box_id_){}
    , decltype(_impl_.xwalk_local_index_){}
    , decltype(_impl_.module_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.client_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_address().empty()) {
    _this->_impl_.client_address_.Set(from._internal_client_address(),
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.mail_box_id_, &from._impl_.mail_box_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.module_type_) -
    reinterpret_cast<char*>(&_impl_.mail_box_id_)) + sizeof(_impl_.module_type_));
  // @@protoc_insertion_point(copy_constructor:xwalk.iw.v1.XClientAddress)
}

inline void XClientAddress::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.client_address_){}
    , decltype(_impl_.mail_box_id_){0u}
    , decltype(_impl_.xwalk_local_index_){0u}
    , decltype(_impl_.module_type_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.client_address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XClientAddress::~XClientAddress() {
  // @@protoc_insertion_point(destructor:xwalk.iw.v1.XClientAddress)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XClientAddress::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.client_address_.Destroy();
}

void XClientAddress::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XClientAddress::Clear() {
// @@protoc_insertion_point(message_clear_start:xwalk.iw.v1.XClientAddress)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_address_.ClearToEmpty();
  ::memset(&_impl_.mail_box_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.module_type_) -
      reinterpret_cast<char*>(&_impl_.mail_box_id_)) + sizeof(_impl_.module_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XClientAddress::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 mail_box_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.mail_box_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string client_address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_client_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "xwalk.iw.v1.XClientAddress.client_address"));
        } else
          goto handle_unusual;
        continue;
      // uint32 xwalk_local_index = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.xwalk_local_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 module_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.module_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XClientAddress::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xwalk.iw.v1.XClientAddress)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 mail_box_id = 1;
  if (this->_internal_mail_box_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_mail_box_id(), target);
  }

  // string client_address = 2;
  if (!this->_internal_client_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_address().data(), static_cast<int>(this->_internal_client_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "xwalk.iw.v1.XClientAddress.client_address");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_client_address(), target);
  }

  // uint32 xwalk_local_index = 3;
  if (this->_internal_xwalk_local_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_xwalk_local_index(), target);
  }

  // uint32 module_type = 4;
  if (this->_internal_module_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_module_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xwalk.iw.v1.XClientAddress)
  return target;
}

size_t XClientAddress::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xwalk.iw.v1.XClientAddress)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_address = 2;
  if (!this->_internal_client_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_address());
  }

  // uint32 mail_box_id = 1;
  if (this->_internal_mail_box_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_mail_box_id());
  }

  // uint32 xwalk_local_index = 3;
  if (this->_internal_xwalk_local_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_xwalk_local_index());
  }

  // uint32 module_type = 4;
  if (this->_internal_module_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_module_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XClientAddress::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XClientAddress::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XClientAddress::GetClassData() const { return &_class_data_; }


void XClientAddress::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XClientAddress*>(&to_msg);
  auto& from = static_cast<const XClientAddress&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xwalk.iw.v1.XClientAddress)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_address().empty()) {
    _this->_internal_set_client_address(from._internal_client_address());
  }
  if (from._internal_mail_box_id() != 0) {
    _this->_internal_set_mail_box_id(from._internal_mail_box_id());
  }
  if (from._internal_xwalk_local_index() != 0) {
    _this->_internal_set_xwalk_local_index(from._internal_xwalk_local_index());
  }
  if (from._internal_module_type() != 0) {
    _this->_internal_set_module_type(from._internal_module_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XClientAddress::CopyFrom(const XClientAddress& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xwalk.iw.v1.XClientAddress)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XClientAddress::IsInitialized() const {
  return true;
}

void XClientAddress::InternalSwap(XClientAddress* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.client_address_, lhs_arena,
      &other->_impl_.client_address_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XClientAddress, _impl_.module_type_)
      + sizeof(XClientAddress::_impl_.module_type_)
      - PROTOBUF_FIELD_OFFSET(XClientAddress, _impl_.mail_box_id_)>(
          reinterpret_cast<char*>(&_impl_.mail_box_id_),
          reinterpret_cast<char*>(&other->_impl_.mail_box_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata XClientAddress::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto_getter, &descriptor_table_xHal_5fRpi5CarXIwMessageCmn_2eproto_once,
      file_level_metadata_xHal_5fRpi5CarXIwMessageCmn_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace iw
}  // namespace xwalk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::xwalk::iw::v1::XClientAddress*
Arena::CreateMaybeMessage< ::xwalk::iw::v1::XClientAddress >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xwalk::iw::v1::XClientAddress >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
