include_guard(GLOBAL)

set(XWALK_LIBRARY_ROOT "${CMAKE_CURRENT_LIST_DIR}" CACHE PATH
    "Root of the reviewed project-managed dependency library")

string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" XWALK_LIBRARY_DETECTED_PROCESSOR)
if(XWALK_LIBRARY_DETECTED_PROCESSOR MATCHES "^(aarch64|arm64)$")
    set(XWALK_LIBRARY_DETECTED_ARCHITECTURE aarch64)
elseif(XWALK_LIBRARY_DETECTED_PROCESSOR MATCHES "^(x86_64|amd64)$")
    set(XWALK_LIBRARY_DETECTED_ARCHITECTURE x86_64)
else()
    set(XWALK_LIBRARY_DETECTED_ARCHITECTURE unsupported)
endif()

set(XWALK_LIBRARY_ARCHITECTURE
    "${XWALK_LIBRARY_DETECTED_ARCHITECTURE}" CACHE STRING
    "Project-managed native dependency architecture: aarch64 or x86_64")
set_property(CACHE XWALK_LIBRARY_ARCHITECTURE PROPERTY STRINGS aarch64 x86_64)

if(NOT XWALK_LIBRARY_ARCHITECTURE STREQUAL "aarch64" AND
    NOT XWALK_LIBRARY_ARCHITECTURE STREQUAL "x86_64")
    message(FATAL_ERROR
        "xWalkLibrary has no native prefix for processor '${CMAKE_SYSTEM_PROCESSOR}'. "
        "Set XWALK_LIBRARY_ARCHITECTURE to aarch64 or x86_64 for a supported target.")
endif()

set(XWALK_LIBRARY_COMMON_PREFIX "${XWALK_LIBRARY_ROOT}/common")
set(XWALK_LIBRARY_NATIVE_PREFIX
    "${XWALK_LIBRARY_ROOT}/${XWALK_LIBRARY_ARCHITECTURE}")

option(XWALK_LIBRARY_PREFER_PROJECT_DEPENDENCIES
    "Search xWalkLibrary before system prefixes for portable dependencies" ON)
option(XWALK_LIBRARY_USE_BUILD_RPATH
    "Embed the selected xWalkLibrary native library directories in build-tree binaries" ON)

if(XWALK_LIBRARY_PREFER_PROJECT_DEPENDENCIES)
    list(PREPEND CMAKE_PREFIX_PATH
        "${XWALK_LIBRARY_NATIVE_PREFIX}"
        "${XWALK_LIBRARY_COMMON_PREFIX}")
endif()

if(XWALK_LIBRARY_USE_BUILD_RPATH)
    list(APPEND CMAKE_BUILD_RPATH
        "${XWALK_LIBRARY_NATIVE_PREFIX}/lib"
        "${XWALK_LIBRARY_NATIVE_PREFIX}/lib64")
    list(REMOVE_DUPLICATES CMAKE_BUILD_RPATH)
endif()

message(STATUS
    "xWalk project dependency prefix: ${XWALK_LIBRARY_NATIVE_PREFIX} "
    "(project-first search: ${XWALK_LIBRARY_PREFER_PROJECT_DEPENDENCIES})")
