/******************************************************************************
 * @file        xHal_Rpi5CarServoTestI2c.h
 * @brief       Declares the in-memory I2C recorder used by Servo host tests.
 *
 * @details
 * Supplies callbacks for a separately created `XWalkI2c` object and records
 * register addresses and payloads without accessing physical hardware.
 *
 * @project     xWalk Firmware
 * @module      xWalkServo Host Test
 *
 * @author      Joxy John
 * @date        2026-07-29
 * @version     1.0.0
 *
 * @copyright
 * Copyright (c) 2026 Joxy John.
 * All rights reserved.
 *
 * @note
 * Developed using MISRA C++ coding guidelines.
 ******************************************************************************/

#ifndef XHAL_RPI5CAR_SERVO_TEST_I2C_H
#define XHAL_RPI5CAR_SERVO_TEST_I2C_H

/******************************************************************************
 * Includes
 ******************************************************************************/

#include "xHal_Rpi5CarI2c.h"

/******************************************************************************
 * Namespace declarations
 ******************************************************************************/

/**
 * @namespace xwalk::hal::test
 * @brief Contains host-side verification components for the xWalk HAL.
 */
namespace xwalk::hal::test
{

    /******************************************************************************
     * Class declarations
     ******************************************************************************/

    /**
     * @class XWalkServoTestI2c
     * @brief Records I2C writes generated by PWM and Servo operations.
     *
     * @details
     * Stores deep copies of register addresses and payloads. Each test creates a
     * separate callback interface whose non-owning context points to this object.
     */
    class XWalkServoTestI2c
    {
        private:
            /**************************************************************************
             * Private data members
             **************************************************************************/

            /** @brief Ordered record of written eight-bit register addresses. */
            bytevector writeRegisters;

            /** @brief Ordered deep copies of register-write payloads. */
            bytevectorvector writePayloads;

        public:
            /**************************************************************************
             * Public constructors and destructor
             **************************************************************************/

            /** @brief Constructs an empty in-memory I2C recorder. */
            XWalkServoTestI2c();

            /** @brief Destroys the recorder and its stored payloads. */
            ~XWalkServoTestI2c();

            /**************************************************************************
             * Public member functions
             **************************************************************************/

            /**
             * @brief Simulates an I2C probe with no responding device.
             *
             * @param[in] context
             * Non-owning callback context; unused by this probe implementation.
             *
             * @param[in] address
             * Seven-bit I2C address; unused by this probe implementation.
             *
             * @return
             * Always `false`.
             */
            static boolean probeCallback(contextpointer context, uint8 address);

            /**
             * @brief Records one simulated register write.
             *
             * @param[in,out] context
             * Non-null pointer to the `XWalkServoTestI2c` recorder.
             *
             * @param[in] address
             * Seven-bit destination address; accepted but not stored.
             *
             * @param[in] reg
             * Eight-bit destination register address.
             *
             * @param[in] data
             * Payload bytes copied into recorder-owned storage.
             */
            static void writeRegisterCallback(contextpointer context, uint8 address, uint8 reg, const bytevector& data);

            /**
             * @brief Returns zero-filled bytes for interfaces that require a read callback.
             *
             * @param[in] context
             * Non-owning callback context; unused by this implementation.
             *
             * @param[in] address
             * Seven-bit source address; unused by this implementation.
             *
             * @param[in] length
             * Number of zero-filled bytes to return.
             *
             * @return
             * A byte vector of size `length` containing zero values.
             */
            static bytevector readCallback(contextpointer context, uint8 address, size length);

            /**
             * @brief Returns the number of recorded register writes.
             *
             * @return
             * Number of writes recorded since construction or clearing.
             */
            size writeCount() const noexcept;

            /** @brief Clears every recorded register and payload. */
            void clearWrites() noexcept;

            /**
             * @brief Returns a recorded register address.
             *
             * @param[in] index
             * Zero-based write index in the range 0 to `writeCount() - 1`.
             *
             * @return
             * Eight-bit register address stored at `index`.
             */
            uint8 writeRegister(size index) const;

            /**
             * @brief Returns a recorded register payload.
             *
             * @param[in] index
             * Zero-based write index in the range 0 to `writeCount() - 1`.
             *
             * @return
             * Read-only reference to the payload stored at `index`.
             */
            const bytevector& writeData(size index) const;
    };

} /* namespace xwalk::hal::test */

#endif /* XHAL_RPI5CAR_SERVO_TEST_I2C_H */
