/******************************************************************************
 * @file        xHal_Rpi5CarMusicTone.cpp
 * @brief       Implements signed PCM tone generation and output forwarding.
 *
 * @details
 * Produces the Python port's duration-adjusted sine samples as little-endian
 * signed 16-bit mono PCM and passes generated data to the injected backend.
 *
 * @project     xWalk Firmware
 * @module      xWalkMusic
 *
 * @author      Joxy John
 * @date        2026-07-29
 * @version     1.0.0
 *
 * @copyright
 * Copyright (c) 2026 Joxy John.
 * All rights reserved.
 *
 * @note
 * Developed using MISRA C++ coding guidelines.
 ******************************************************************************/

/******************************************************************************
 * Includes
 ******************************************************************************/

#include "xHal_Rpi5CarMusic.h"

#include "xHal_Rpi5CarTrace.h"

/******************************************************************************
 * Namespace definitions
 ******************************************************************************/

/**
 * @namespace xwalk::hal
 * @brief Contains hardware abstraction components for the xWalk firmware.
 */
namespace xwalk::hal
{

    /******************************************************************************
     * Public member function definitions
     ******************************************************************************/

    /**
     * @brief Generates Python-compatible signed 16-bit mono PCM tone data.
     *
     * @param[in] frequencyHz
     * Finite frequency greater than zero, in Hertz.
     *
     * @param[in] durationSeconds
     * Finite non-negative requested duration in seconds.
     *
     * @return
     * Little-endian PCM bytes at 44,100 Hertz.
     *
     * @note
     * Compatibility requires halving the requested duration and appending
     * `frameCount % sampleRate` silent samples, matching the Python source.
     *
     * @throws std::invalid_argument
     * If frequency or duration is not finite, or frequency is not positive.
     *
     * @throws std::out_of_range
     * If duration is negative or the generated byte count exceeds the supported
     * range.
     */
    bytevector XWalkMusic::getToneData(float64 frequencyHz, float64 durationSeconds) const
    {
        validateTone(frequencyHz, durationSeconds);

        const float64 adjustedDurationSeconds = durationSeconds / XHAL_RPI5CAR_MUSIC_TONE_DURATION_DIVISOR;
        const float64 sampleRateHz = static_cast<float64>(XHAL_RPI5CAR_MUSIC_SAMPLE_RATE_HZ);
        const float64 frameCountValue = sampleRateHz * adjustedDurationSeconds;
        const float64 maximumFrameCount = static_cast<float64>(XHAL_RPI5CAR_UINT32_MAX);
        if (frameCountValue > maximumFrameCount)
        {
            XWALK_HAL_ERROR(XWALK_RANGE, "Music tone duration produces too many PCM frames");
        }

        const uint32 frameCount = static_cast<uint32>(frameCountValue);
        const uint32 remainderFrameCount = frameCount % XHAL_RPI5CAR_MUSIC_SAMPLE_RATE_HZ;
        const uint64 sampleCount = static_cast<uint64>(frameCount) + static_cast<uint64>(remainderFrameCount);
        const uint64 sampleBytes = static_cast<uint64>(XHAL_RPI5CAR_MUSIC_SAMPLE_BYTES);
        const uint64 byteCount = sampleCount * sampleBytes;
        if (byteCount > static_cast<uint64>(XHAL_RPI5CAR_UINT32_MAX))
        {
            XWALK_HAL_ERROR(XWALK_RANGE, "Music tone byte count exceeds the supported range");
        }

        bytevector pcmData(static_cast<size>(byteCount), 0U);
        const float64 framesPerWave = sampleRateHz / frequencyHz;
        for (uint32 frameIndex = 0U; frameIndex < frameCount; ++frameIndex)
        {
            const float64 framePosition = static_cast<float64>(frameIndex);
            const float64 wavePosition = framePosition / framesPerWave;
            const float64 angleRadians = wavePosition * XHAL_RPI5CAR_MUSIC_TWO_PI_RADIANS;
            const float64 sineValue = XHAL_SINE(angleRadians);
            const float64 sampleValue = sineValue * XHAL_RPI5CAR_MUSIC_SAMPLE_PEAK;
            const int32 signedSample = static_cast<int32>(sampleValue);
            const uint16 packedSample = static_cast<uint16>(signedSample);
            const uint16 lowByteValue = packedSample & XHAL_RPI5CAR_MUSIC_SAMPLE_BYTE_MASK;
            const uint16 highByteValue = packedSample >> XHAL_RPI5CAR_MUSIC_SAMPLE_HIGH_BYTE_SHIFT;
            const size outputIndex = static_cast<size>(frameIndex) * XHAL_RPI5CAR_MUSIC_SAMPLE_BYTES;
            pcmData[outputIndex + XHAL_RPI5CAR_MUSIC_SAMPLE_LOW_BYTE_INDEX] = static_cast<uint8>(lowByteValue);
            pcmData[outputIndex + XHAL_RPI5CAR_MUSIC_SAMPLE_HIGH_BYTE_INDEX] = static_cast<uint8>(highByteValue);
        }
        XWALK_HAL_TRACE_UID2(RPI .300, "Generated %zu PCM tone bytes at %.2f Hz", pcmData.size(), frequencyHz);
        return pcmData;
    }

    /**
     * @brief Generates and writes one tone through the injected backend.
     *
     * @param[in] frequencyHz
     * Finite frequency greater than zero, in Hertz.
     *
     * @param[in] durationSeconds
     * Finite non-negative requested duration in seconds.
     *
     * @throws std::invalid_argument
     * If frequency or duration is not finite, or frequency is not positive.
     *
     * @throws std::out_of_range
     * If duration is negative or the generated byte count exceeds the supported
     * range.
     */
    void XWalkMusic::playToneFor(float64 frequencyHz, float64 durationSeconds)
    {
        const bytevector pcmData = getToneData(frequencyHz, durationSeconds);
        callbacks.playTone(
            backendContext, pcmData, XHAL_RPI5CAR_MUSIC_SAMPLE_RATE_HZ, XHAL_RPI5CAR_MUSIC_CHANNEL_COUNT);
        XWALK_HAL_TRACE_UID1(RPI .301, "PCM tone playback completed at %.2f Hz", frequencyHz);
    }

    /******************************************************************************
     * Protected member function definitions
     ******************************************************************************/

    /**
     * @brief Validates generated-tone frequency and duration.
     *
     * @param[in] frequencyHz
     * Finite frequency greater than zero, in Hertz.
     *
     * @param[in] durationSeconds
     * Finite non-negative requested duration in seconds.
     *
     * @throws std::invalid_argument
     * If either argument is not finite or the frequency is not positive.
     *
     * @throws std::out_of_range
     * If the duration is negative.
     */
    void XWalkMusic::validateTone(float64 frequencyHz, float64 durationSeconds)
    {
        const hal::boolean frequencyHzDurationSecondsInvalid =
            static_cast<hal::boolean>(!XHAL_IS_FINITE(frequencyHz) || !XHAL_IS_FINITE(durationSeconds));
        if (frequencyHzDurationSecondsInvalid)
        {
            XWALK_HAL_ERROR(XWALK_INVAL, "Music tone frequency and duration must be finite");
        }
        if (frequencyHz <= 0.0)
        {
            XWALK_HAL_ERROR(XWALK_INVAL, "Music tone frequency must be greater than zero");
        }
        if (durationSeconds < 0.0)
        {
            XWALK_HAL_ERROR(XWALK_RANGE, "Music tone duration must not be negative");
        }
    }

} /* namespace xwalk::hal */
